"""Team name configuration and mappings.

Forked from cfb-grid-python/mern/python/v2/config/teams.py as of the
BigQuery-transform migration. Keep both copies in sync until/unless this
becomes a shared, single-sourced lookup.
"""

TEAM_NAME_SUBSTITUTIONS = {
    'Abilene Christian': 'Abilene Chr.',
    'Air Force': 'Air Force',
    'Akron': 'Akron',
    'Alabama': 'Alabama',
    'Alabama A&M': 'Alabama A&M',
    'Alabama State': 'Alabama St.',
    'UAlbany': 'Albany',
    'Albany State (GA)': 'Albany St. (GA)',
    'Alcorn State': 'Alcorn St.',
    'Allen': 'Allen',
    'App State': 'Appalachian St.',
    'Arizona': 'Arizona',
    'Arizona State': 'Arizona St.',
    'Arkansas': 'Arkansas',
    'Arkansas-Pine Bluff': 'Ark.-Pine Bluff',
    'Arkansas State': 'Arkansas St.',
    'Army': 'Army',
    'Auburn': 'Auburn',
    'Austin Peay': 'Austin Peay',
    'Ball State': 'Ball St.',
    'Baylor': 'Baylor',
    'Benedict College': 'Benedict Coll.',
    'Bethune-Cookman': 'Bethune-Cookman',
    'Boise State': 'Boise St.',
    'Boston College': 'Boston College',
    'Bowling Green': 'Bowling Green',
    'Brown': 'Brown',
    'Bryant': 'Bryant',
    'Bucknell': 'Bucknell',
    'Buffalo': 'Buffalo',
    'Butler': 'Butler',
    'BYU': 'BYU',
    'California': 'California',
    'Cal Poly': 'Cal Poly',
    'Campbell': 'Campbell',
    'Carson-Newman': 'Carson-Newman',
    'Central Arkansas': 'C. Arkansas',
    'Central Connecticut': 'C. Connecticut',
    'Central Michigan': 'C. Michigan',
    'Central State': 'Central St.',
    'Chadron St': 'Chadron St.',
    'Charleston Southern': 'Charleston So.',
    'Charlotte': 'Charlotte',
    'Chattanooga': 'Chattanooga',
    'Cincinnati': 'Cincinnati',
    'Clark Atlanta': 'Clark Atlanta',
    'Clemson': 'Clemson',
    'Coastal Carolina': 'C. Carolina',
    'Colgate': 'Colgate',
    'Colorado': 'Colorado',
    'Colorado Mesa': 'Colorado Mesa',
    'Colorado State': 'Colorado St.',
    'Columbia': 'Columbia',
    'UConn': 'UConn',
    'Cornell': 'Cornell',
    'Cumberland (TN)': 'Cumberland (TN)',
    'Dartmouth': 'Dartmouth',
    'Davidson': 'Davidson',
    'Dayton': 'Dayton',
    'Delaware': 'Delaware',
    'Delaware State': 'Delaware St.',
    'Drake': 'Drake',
    'Duke': 'Duke',
    'Duquesne': 'Duquesne',
    'East Carolina': 'East Carolina',
    'Eastern Illinois': 'E. Illinois',
    'Eastern Kentucky': 'E. Kentucky',
    'Eastern Michigan': 'E. Michigan',
    'Eastern Washington': 'E. Washington',
    'East Tennessee State': 'ETSU',
    'Edward Waters': 'Edward Waters',
    'Elon': 'Elon',
    'Fayetteville State': 'Fayetteville St.',
    'Ferris State': 'Ferris St.',
    'Florida': 'Florida',
    'Florida A&M': 'Florida A&M',
    'Florida Atlantic': 'FAU',
    'Florida International': 'FIU',
    'Florida Memorial University': 'Fla. Memorial',
    'Florida State': 'Florida St.',
    'Fordham': 'Fordham',
    'Fort Valley State': 'Fort Valley St.',
    'Fresno State': 'Fresno St.',
    'Furman': 'Furman',
    'Gardner-Webb': 'Gardner-Webb',
    'Georgetown': 'Georgetown',
    'Georgia': 'Georgia',
    'Georgia Southern': 'Georgia So.',
    'Georgia State': 'Georgia St.',
    'Georgia Tech': 'Georgia Tech',
    'Grambling': 'Grambling',
    'Hampton': 'Hampton',
    'Harvard': 'Harvard',
    "Hawai'i": 'Hawaii',
    'Holy Cross': 'Holy Cross',
    'Houston': 'Houston',
    'Houston Christian': 'Houston Chr.',
    'Howard': 'Howard',
    'Idaho': 'Idaho',
    'Idaho State': 'Idaho St.',
    'Illinois': 'Illinois',
    'Illinois State': 'Illinois St.',
    'Incarnate Word': 'Incarnate Word',
    'Indiana': 'Indiana',
    'Indiana State': 'Indiana St.',
    'Indiana Wesleyan': 'Ind. Wesleyan',
    'Iowa': 'Iowa',
    'Iowa State': 'Iowa St.',
    'Jackson State': 'Jackson St.',
    'Jacksonville State': "Jacksonville St.",
    'James Madison': 'James Madison',
    'Kansas': 'Kansas',
    'Kansas State': 'Kansas St.',
    'Kennesaw State': 'Kennesaw St.',
    'Kent State': 'Kent St.',
    'Kentucky': 'Kentucky',
    'Kentucky State': 'Kentucky St.',
    'Lafayette': 'Lafayette',
    'Lamar': 'Lamar',
    'Lane': 'Lane',
    'Lehigh': 'Lehigh',
    'Liberty': 'Liberty',
    'Lincoln University (CA)': 'Lincoln (CA)',
    'Lindenwood': 'Lindenwood',
    'Little Rock': 'Ark. Baptist',
    'Long Island University': 'LIU',
    'Louisiana': 'Louisiana',
    'UL Monroe': 'ULM',
    'Louisiana Tech': 'La. Tech',
    'Louisville': 'Louisville',
    'LSU': 'LSU',
    'Maine': 'Maine',
    'Marist': 'Marist',
    'Marshall': 'Marshall',
    'Maryland': 'Maryland',
    'McNeese': 'McNeese',
    'Memphis': 'Memphis',
    'Mercer': 'Mercer',
    'Merrimack': 'Merrimack',
    'Miami': 'Miami (FL)',
    'Miami (OH)': 'Miami (OH)',
    'Michigan': 'Michigan',
    'Michigan State': 'Michigan St.',
    'Middle Tennessee': 'MTSU',
    'Miles': 'Miles',
    'Minnesota': 'Minnesota',
    'Mississippi State': 'Mississippi St.',
    'Mississippi Valley State': 'MVSU',
    'Missouri': 'Missouri',
    'Missouri State': 'Missouri St.',
    'Monmouth': 'Monmouth',
    'Montana': 'Montana',
    'Montana State': 'Montana St.',
    'Morehead State': 'Morehead St.',
    'Morehouse': 'Morehouse',
    'Morgan State': 'Morgan St.',
    'Murray State': 'Murray St.',
    'Navy': 'Navy',
    'NC State': 'NC State',
    'Nebraska': 'Nebraska',
    'Nevada': 'Nevada',
    'New Hampshire': 'New Hampshire',
    'New Mexico': 'New Mexico',
    'New Mexico State': 'New Mexico St.',
    'Nicholls': 'Nicholls',
    'Norfolk State': 'Norfolk St.',
    'North Alabama': 'North Alabama',
    'North American University': 'North American',
    'North Carolina': 'North Carolina',
    'North Carolina A&T': 'N. Carolina A&T',
    'North Carolina Central': 'NC Central',
    'North Dakota': 'North Dakota',
    'North Dakota State': 'N. Dakota St.',
    'Northern Arizona': 'N. Arizona',
    'Northern Colorado': 'N. Colorado',
    'Northern Illinois': 'N. Illinois',
    'Northern Iowa': 'N. Iowa',
    'North Texas': 'North Texas',
    'Northwestern': 'Northwestern',
    'Northwestern (IA)': 'N\'Western (IA)',
    'Northwestern State': 'NW State',
    'Notre Dame': 'Notre Dame',
    'Ohio': 'Ohio',
    'Ohio State': 'Ohio St.',
    'Oklahoma': 'Oklahoma',
    'Oklahoma State': 'Oklahoma St.',
    'Old Dominion': 'Old Dominion',
    'Ole Miss': 'Ole Miss',
    'Oregon': 'Oregon',
    'Oregon State': 'Oregon St.',
    'Penn State': 'Penn St.',
    'Pennsylvania': 'Penn',
    'Pittsburgh': 'Pittsburgh',
    'Portland State': 'Portland St.',
    'Prairie View A&M': 'Prairie View',
    'Presbyterian College': 'Presbyterian',
    'Princeton': 'Princeton',
    'Purdue': 'Purdue',
    'Rhode Island': 'Rhode Island',
    'Rice': 'Rice',
    'Richmond': 'Richmond',
    'Robert Morris': 'Robert Morris',
    'Rutgers': 'Rutgers',
    'Sacramento State': 'Sac. State',
    'Sacred Heart': 'Sacred Heart',
    'Samford': 'Samford',
    'Sam Houston': 'S. Houston St.',
    'San Diego': 'San Diego',
    'San Diego State': 'San Diego St.',
    'San José State': 'San Jose St.',
    'Savannah State': 'Savannah St.',
    'SMU': 'SMU',
    'South Alabama': 'South Alabama',
    'South Carolina': 'South Carolina',
    'South Carolina State': 'South Carolina St.',
    'South Dakota': 'South Dakota',
    'South Dakota State': 'South Dakota St.',
    'SE Louisiana': 'SE Louisiana',
    'Southeast Missouri State': 'SE Missouri St.',
    'Southern': 'Southern',
    'Southern Illinois': 'S. Illinois',
    'Southern Miss': 'Southern Miss',
    'Southern Utah': 'S. Utah',
    'Southwest Baptist': 'Southwest Bapt.',
    'Southwest Minnesota State': 'SW Minnesota St.',
    'South Florida': 'USF',
    'Stanford': 'Stanford',
    'Stephen F. Austin': 'S.F. Austin',
    'Stetson': 'Stetson',
    'St. Francis (PA)': 'St. Francis (PA)',
    'Stonehill': 'Stonehill',
    'Stony Brook': 'Stony Brook',
    'St. Thomas (MN)': 'St. Thomas (MN)',
    'Sul Ross State': 'Sul Ross St.',
    'Syracuse': 'Syracuse',
    'Tarleton State': 'Tarleton St.',
    'TCU': 'TCU',
    'Temple': 'Temple',
    'Tennessee': 'Tennessee',
    'Tennessee State': 'Tennessee St.',
    'Tennessee Tech': 'Tennessee Tech',
    'Texas': 'Texas',
    'Texas A&M': 'Texas A&M',
    'East Texas A&M': 'East Texas A&M',
    'Texas College': 'Texas College',
    'Texas Southern': 'Texas So.',
    'Texas State': 'Texas St.',
    'Texas Tech': 'Texas Tech',
    'The Citadel': 'The Citadel',
    'Toledo': 'Toledo',
    'Towson': 'Towson',
    'Troy': 'Troy',
    'Tulane': 'Tulane',
    'Tulsa': 'Tulsa',
    'Tuskegee': 'Tuskegee',
    'UAB': 'UAB',
    'UC Davis': 'UC Davis',
    'UCF': 'UCF',
    'UCLA': 'UCLA',
    'Massachusetts': 'UMass',
    'UNLV': 'UNLV',
    'Upper Iowa University': 'Upper Iowa',
    'USC': 'USC',
    'Utah': 'Utah',
    'Utah State': 'Utah St.',
    'Utah Tech': 'Utah Tech',
    'UTEP': 'UTEP',
    'UT Martin': 'UT Martin',
    'UT Rio Grande Valley': 'UTRGV',
    'UTSA': 'UTSA',
    'Valparaiso': 'Valparaiso',
    'Vanderbilt': 'Vanderbilt',
    'Villanova': 'Villanova',
    'Virginia': 'Virginia',
    'Virginia Tech': 'Virginia Tech',
    'Virginia University Of Lynchburg': 'Va.-Lynchburg',
    'VMI': 'VMI',
    'Wagner': 'Wagner',
    'Wake Forest': 'Wake Forest',
    'Washington': 'Washington',
    'Washington State': 'Washington St.',
    'Webber International': 'Webber Int\'l',
    'Weber State': 'Weber St.',
    'West Georgia': 'West Georgia',
    'Western Carolina': 'W. Carolina',
    'Western Illinois': 'W. Illinois',
    'Western Kentucky': 'W. Kentucky',
    'Western Michigan': 'W. Michigan',
    'West Virginia': 'West Virginia',
    'William & Mary': 'William & Mary',
    'Wisconsin': 'Wisconsin',
    'Wofford': 'Wofford',
    'Wyoming': 'Wyoming',
    'Yale': 'Yale',
    'Youngstown State': 'Youngstown St.',
    'Dixie State': 'Utah Tech',
    'McKendree': 'McKendree',
    'Louisiana College': 'Louisiana Christian',
    'Warner University': 'Warner',
    'Virginia St': 'Virginia St.',
    'Central Washington': 'C. Washington',
    'Bowie State': 'Bowie St.',
    'Langston University': 'Langston',
    'Northeastern State': 'Northeastern St.',
    'ERSKINE': 'Erskine',
    'Western Oregon': 'W. Oregon',
    'BLUEFIELD': 'Bluefield',
    'Kentucky Christian': 'Kentucky Chr.',
    'Greensboro College': 'Greensboro',
    'Southern Connecticut State': 'S. Connecticut',
    'Albany State GA': 'Albany St. (GA)',
    'Merchant Marine Academy': 'Merchant Marine',
    'PennWest California': 'California (PA)',
    'Frostburg State': 'Frostburg St.',
    'Springfield': 'Springfield',
    'Johns Hopkins University': 'Johns Hopkins',
    'Susquehanna': 'Susquehanna',
    'Christopher Newport': 'Chris. Newport',
    'Lagrange College': 'LaGrange',
    'Berry College': 'Berry',
    'Assumption': 'Assumption',
    'Kutztown University': 'Kutztown',
    'Muhlenberg': 'Muhlenberg',
    'University of Mount Union': 'Mount Union',
    'Ashland': 'Ashland',
    'Wheaton': 'Wheaton',
    'Wartburg': 'Wartburg',
    'Chapman': 'Chapman',
    'Wisconsin-River Falls': 'WI-River Falls',
    'Newberry': 'Newberry',
    'West Florida': 'West Florida',
    'Hanover College': 'Hanover',
    'North Central College': 'North Central',
    'Coe College': 'Coe',
    'Bethel (MN)': 'Bethel (MN)',
    'Harding University': 'Harding',
    'Pittsburg St': 'Pittsburg St.',
    'Minnesota State Mankato': 'MN St. Mankato',
    'Indianapolis': 'Indianapolis',
    'Western Colorado': 'W. Colorado',
    'UT Permian Basin': 'UT Permian Basin',
    'Salisbury': 'Salisbury',
    'John Carroll University': 'John Carroll',
    "Saint John's (MN)": "Saint John's (MN)",
    'Wisconsin-Lacrosse': 'WI-La Crosse',
    'Wisconsin-Platteville': 'WI-Platteville',
    'Eastern University': 'Eastern',
    'Trinity University TX': 'Trinity (TX)',
    'Depauw': 'Depauw',
}
